// Objective-C API for talking to bitbucket.org/karolis-proxies-project/mobile-sdk Go package.
//   gobind -lang=objc bitbucket.org/karolis-proxies-project/mobile-sdk
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_sdk_H__
#define __Mobile_sdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol Mobile_sdkEventCallback;
@class Mobile_sdkEventCallback;

@protocol Mobile_sdkEventCallback <NSObject>
- (void)onEvent:(NSString* _Nullable)p0;
@end

@interface Mobile_sdk : NSObject
+ (NSString* _Nonnull) version;
+ (void) setVersion:(NSString* _Nonnull)v;

@end

FOUNDATION_EXPORT void Mobile_sdkInitialize(NSString* _Nullable deviceId, NSString* _Nullable deviceName);

FOUNDATION_EXPORT void Mobile_sdkStartMainRoutine(NSString* _Nullable accessToken, id<Mobile_sdkEventCallback> _Nullable callback);

FOUNDATION_EXPORT void Mobile_sdkStopMainRoutine(void);

@class Mobile_sdkEventCallback;

@interface Mobile_sdkEventCallback : NSObject <goSeqRefInterface, Mobile_sdkEventCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onEvent:(NSString* _Nullable)p0;
@end

#endif
