
// Objective-C API for talking to the following Go packages
//
//	bitbucket.org/karolis-proxies-project/mobile-sdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobile_sdk_FRAMEWORK_H__
#define __Mobile_sdk_FRAMEWORK_H__

#include "Mobile_sdk.objc.h"
#include "Universe.objc.h"

#endif
